import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/provider/providers';
import Header from '@/components/common/Header';
import { AuthProvider } from '@/provider/authProvider';

export const pretendard = localFont({
  src: './fonts/PretendardVariable.ttf',
  display: 'swap',
  weight: '400',
  variable: '--font-pretendard'
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export const metadata: Metadata = {
  title: 'DONT WORRY',
  description: '당신의 걱정을 들어드릴게요',
  openGraph: {
    title: 'DONT WORRY',
    description: '당신의 걱정을 들어드릴게요',
    url: 'https://dontworry.io.kr',
    images: [
      {
        url: 'https://dontworry.io.kr/images/Thumbnail2.png',
        width: 1200,
        height: 630,
        alt: 'DONT WORRY Thumbnail'
      }
    ],
    type: 'website'
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className}`}>
        <Providers>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
