import Text from '@/components/common/Text';
import TimeFilterGroup from '@/components/ranking/FusionComp/TimeFilterGroup';
import { CHART_PAGE_TITLE } from '@/constants/ranking/Line';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RankingLayout = ({
  children
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className="w-full flex justify-center">
      <div className="xl:bg-backgroundSet-normal w-full max-w-[1280px] mx-auto">{/*마지막 3개의 속성을 루트에서 적용시켜야함*/}
        <div className="pr-[6px] pl-[6px] h-14 flex items-center justify-center">
          <Text
            as="h1"
            variant="title1"
            color="label-normal"
            className="text-center border-gray-200 w-full"
          >
            {CHART_PAGE_TITLE}
          </Text>
        </div>
        <div className="py-5 xl:py-6 xl:flex xl:gap-4 xl:h-16 xl:justify-center xl:items-center xl:bg-backgroundSet-card">
          <TimeFilterGroup />
        </div>
        {children}
      </div>
    </div>
  );
};

export default RankingLayout;
