import TimeFilterGroup from '@/components/ranking/FusionComp/TimeFilterGroup';
import { CHART_PAGE_TITLE } from '@/constants/ranking/Line';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RankingLayout = ({
  children
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className="h-100">
      <h1 className="text-center text-2xl text-label-normal font-bold  border-gray-200 pb-4 pt-6">
        {CHART_PAGE_TITLE}
      </h1>
      <div className="pt-5 pb-5">
        <TimeFilterGroup />
      </div>
      {children}
    </div>
  );
};

export default RankingLayout;
