import Text from '@/components/common/Text';
import TimeFilterGroup from '@/components/ranking/FusionComp/TimeFilterGroup';
import { CHART_PAGE_TITLE } from '@/constants/ranking/Line';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RankingLayout = ({
  children
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div>
      <div className="pr-[6px] pl-[6px] h-14 flex items-center justify-center">
        <Text
          as="h1"
          variant="title1"
          color="label-normal"
          className="text-center border-gray-200 w-full"
        >
          {CHART_PAGE_TITLE}
        </Text>
      </div>
      <div className="pt-5 pb-5">
        <TimeFilterGroup />
      </div>
      {children}
    </div>
  );
};

export default RankingLayout;
